export const positions = [
    "Architekt",
    "Artysta",
    "Bankowiec",
    "Barista",
    "Celnik",
    "Dietetyk",
    "Dziennikarz",
    "Elektryk",
    "Farmaceuta",
    "Fotograf",
    "Fryzjer",
    "Grafik",
    "Informatyk",
    "Kelner",
    "Kierowca",
    "Księgowa",
    "Kucharz",
    "Lekarz",
    "Logistyk",
    "Magazynier",
    "Maszynista",
    "Mechanik",
    "Nauczyciel",
    "Niania",
    "Ochroniarz",
    "Piekarz",
    "Pielęgniarka",
    "Pilot",
    "Policjant",
    "Prawnik",
    "Programista",
    "Psycholog",
    "Ratownik",
    "Redaktor",
    "Sekretarka",
    "Sprzedawca",
    "Taksówkarz",
    "Tłumacz",
    "Weterynarz",
];

export const localizations = [
    "Warszawa",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
];

export const conditions = ["Umowa o pracę", "Umowa zlecenie", "Umowa o dzieło"];
