const data = [
    {
        id: 0,
        pracownik: "Adam Adamski",
        stanowisko: "Programista",
        lokalizacja: ["Warszawa", "Łódź"],
        warunki: "Umowa o pracę",
    },
    {
        id: 1,
        pracownik: "Barbara Bar",
        stanowisko: "Fryzjer",
        lokalizacja: ["Poznań", "Lublin"],
        warunki: "Umowa zlecenie",
    },
    {
        id: 2,
        pracownik: "Cecylia Cnot",
        stanowisko: "Grafik",
        lokalizacja: ["Gdańsk", "Białystok"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 3,
        pracownik: "Dariusz Dolak",
        stanowisko: "Celnik",
        lokalizacja: ["Wrocław", "Kraków"],
        warunki: "Umowa o pracę",
    },
    {
        id: 4,
        pracownik: "Edyta Ernst",
        stanowisko: "Bankowiec",
        lokalizacja: ["Kraków", "Warszawa"],
        warunki: "Umowa zlecenie",
    },
    {
        id: 5,
        pracownik: "Felicja Fanowska",
        stanowisko: "Nauczyciel",
        lokalizacja: ["Szczecin", "Białystok"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 6,
        pracownik: "Gabriel Garnkowski",
        stanowisko: "Barista",
        lokalizacja: ["Łódź", "Wrocław"],
        warunki: "Umowa o pracę",
    },
    {
        id: 7,
        pracownik: "Helena Halna",
        stanowisko: "Lekarz",
        lokalizacja: ["Kraków", "Warszawa"],
        warunki: "Umowa o zlecenie",
    },
    {
        id: 8,
        pracownik: "Iga Igielna",
        stanowisko: "Księgowa",
        lokalizacja: ["Poznań", "Szczecin"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 9,
        pracownik: "Juliusz Jemioła",
        stanowisko: "Kelner",
        lokalizacja: ["Gdańsk", "Lublin"],
        warunki: "Umowa o pracę",
    },
    {
        id: 10,
        pracownik: "Klara Koterska",
        stanowisko: "Policjant",
        lokalizacja: ["Poznań", "Wrocław"],
        warunki: "Umowa o zlecenie",
    },
    {
        id: 11,
        pracownik: "Leon Lipiński",
        stanowisko: "Psycholog",
        lokalizacja: ["Bydgoszcz", "Szczecin"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 12,
        pracownik: "Matylda Majowa",
        stanowisko: "Ratownik",
        lokalizacja: ["Lublin", "Kraków"],
        warunki: "Umowa o pracę",
    },
    {
        id: 13,
        pracownik: "Nadia Nużycka",
        stanowisko: "Niania",
        lokalizacja: ["Wrocław", "Szczecin"],
        warunki: "Umowa o zlecenie",
    },
    {
        id: 14,
        pracownik: "Oliwier Owalny",
        stanowisko: "Farmaceuta",
        lokalizacja: ["Gdańsk", "Lublin"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 15,
        pracownik: "Pamela Przepiórkowska",
        stanowisko: "Dietetyk",
        lokalizacja: ["Łódź", "Poznań"],
        warunki: "Umowa o pracę",
    },
    {
        id: 16,
        pracownik: "Roman Realny",
        stanowisko: "Kucharz",
        lokalizacja: ["Warszawa", "Wrocław"],
        warunki: "Umowa o zlecenie",
    },
    {
        id: 17,
        pracownik: "Sara Sokołowska",
        stanowisko: "Logistyk",
        lokalizacja: ["Kraków", "Poznań"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 18,
        pracownik: "Tomek Tarkowski",
        stanowisko: "Ochroniarz",
        lokalizacja: ["Łódź", "Warszawa"],
        warunki: "Umowa o pracę",
    },
    {
        id: 19,
        pracownik: "Ula Unarna",
        stanowisko: "Pilot",
        lokalizacja: ["Kraków", "Wrocław"],
        warunki: "Umowa o zlecenie",
    },
    {
        id: 20,
        pracownik: "Wiktoria Walowska",
        stanowisko: "Architekt",
        lokalizacja: ["Poznań", "Białystok"],
        warunki: "Umowa o dzieło",
    },
    {
        id: 21,
        pracownik: "Zofia Zapiełowska",
        stanowisko: "Dziennikarz",
        lokalizacja: ["Gdańsk", "Szczecin"],
        warunki: "Umowa o pracę",
    },
];

export default data;
